GET http://localhost:5009/games

###
GET http://localhost:5009/games/1

###
GET  http://localhost:5009/games/test

###
POST http://localhost:5009/games
Content-Type: application/json

{
    "name": "Twenty 20",
    "genreId": 2,
    "price": 21.99,
    "release": "2015-10-30"
}

### Invalid parameters for POST - 1 (missing name and genre & invalid price range)
POST http://localhost:5009/games
Content-Type: application/json

{
    "price": 1000,
    "release": "2015-10-30"
}

### Invalid parameters for POST - 2 (invalid name and genre length)
POST http://localhost:5009/games
Content-Type: application/json

{
    "name": "Peppa Pig kajshdfkajf asdfjasdfkl asdflhajsdkfljh asldfalskdfjh asldkfhalskdjfh",
    "genre": "Kids asdkjfh asdfkjhaskdf asdfkjhasdkf",
    "price": 10,
    "release": "2015-10-30"
}

###
PUT http://localhost:5009/games/1
Content-Type: application/json

{
    "name": "Ring Rivals II",
    "genre": "Boxing",
    "price": 23.59,
    "release": "2000-02-15"
}

### Invalid parameters for PUT - (missing name and genre & invalid price range)
PUT http://localhost:5009/games/1
Content-Type: application/json

{
    "price": 123.59,
    "release": "2000-02-15"
}

### Invalid parameters for PUT - 2 (invalid name and genre length)
PUT http://localhost:5009/games/1
Content-Type: application/json

{
    "name": "Ring Rivals II Ring Rivals II Ring Rivals II Ring Rivals II Ring Rivals II Ring Rivals II Ring Rivals II Ring Rivals II Ring Rivals II Ring Rivals II Ring Rivals II Ring Rivals II",
    "genre": "BoxingBoxingBoxingBoxingBoxingBoxingBoxingBoxingBoxingBoxingBoxingBoxing",
    "price": 23.59,
    "release": "2000-02-15"
}

###
DELETE http://localhost:5009/games/3
Content-Type: application/json